src/Web/Websites/ToscaBlu/ViewModels/Header.cs
using System;

namespace Microsoft.eShopOnContainers.WebMVC.ViewModels
{
    public class Header
    {
        public string Controller { get; set; }
        public string Text { get; set; }
    }
}

src/Web/Websites/ToscaBlu/Controllers/CatalogController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.eShopOnContainers.WebMVC.ViewModels.Pagination;
using Microsoft.eShopOnContainers.WebMVC.Services;
using Microsoft.eShopOnContainers.WebMVC.ViewModels.CatalogViewModels;
using Microsoft.AspNetCore.Http;

namespace Microsoft.eShopOnContainers.WebMVC.Controllers
{
    public class CatalogController : Controller
    {
        private ICatalogService _catalogSvc;

        public CatalogController(ICatalogService catalogSvc) => 
            _catalogSvc = catalogSvc;

        public async Task<IActionResult> Index(int? BrandFilterApplied, int? TypesFilterApplied, int? page, [FromQuery]string errorMsg)
        {
            var itemsPage = 10;
            var catalog = await _catalogSvc.GetCatalogItems(page ?? 0, itemsPage, BrandFilterApplied, TypesFilterApplied);
            var vm = new IndexViewModel()
            {
                CatalogItems = catalog.Data,
                Brands = await _catalogSvc.GetBrands(),
                Types = await _catalogSvc.GetTypes(),
                BrandFilterApplied = BrandFilterApplied ?? 0,
                TypesFilterApplied = TypesFilterApplied ?? 0,
                PaginationInfo = new PaginationInfo()
                {
                    ActualPage = page ?? 0,
                    ItemsPerPage = catalog.Data.Count,
                    TotalItems = catalog.Count, 
                    TotalPages = (int)Math.Ceiling(((decimal)catalog.Count / itemsPage))
                }
            };

            vm.PaginationInfo.Next = (vm.PaginationInfo.ActualPage == vm.PaginationInfo.TotalPages - 1) ? "is-disabled" : "";
            vm.PaginationInfo.Previous = (vm.PaginationInfo.ActualPage == 0) ? "is-disabled" : "";

            ViewBag.BasketInoperativeMsg = errorMsg;

            return View(vm);
        }
    }
}

src/Web/Websites/ToscaBlu/Views/Shared/_Header.cshtml
@model IEnumerable<Microsoft.eShopOnContainers.WebMVC.ViewModels.Header>

<div class="esh-header">
    <div class="container">
        @foreach (var header in @Model)
        {
            <a class="esh-header-back" asp-area="" asp-controller="@header.Controller" asp-action="Index">@header.Text</a>
        }
    </div>
</div>

src/Web/Websites/ToscaBlu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Microsoft.eShopOnContainers.WebMVC</title>

    <environment names="Development">
        <!--
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/app.css" />
    <link rel="stylesheet" href="~/css/app.component.css" />
    <link rel="stylesheet" href="~/css/shared/components/header/header.css" />
    <link rel="stylesheet" href="~/css/shared/components/identity/identity.css" />
    <link rel="stylesheet" href="~/css/shared/components/pager/pager.css" />
    <link rel="stylesheet" href="~/css/basket/basket.component.css" />
    <link rel="stylesheet" href="~/css/campaigns/campaigns.component.css" />
    <link rel="stylesheet" href="~/css/basket/basket-status/basket-status.component.css" />
    <link rel="stylesheet" href="~/css/catalog/catalog.component.css" />
    <link rel="stylesheet" href="~/css/orders/orders.component.css" />
    <link rel="stylesheet" href="~/css/orders/orders-detail/orders-detail.component.css" />
    <link rel="stylesheet" href="~/css/orders/orders-new/orders-new.component.css" />
    <link rel="stylesheet" href="~/css/override.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.min.css" type="text/css" />
        -->

        <link rel="stylesheet" href="~/css/toscablu/Style.css" />
        <link rel="stylesheet" href="~/css/toscablu/Base.css" />
        <link rel="stylesheet" href="~/css/toscablu/Common.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/override.css" type="text/css" />
    </environment>
</head>
<body>
    <div id="page" data-bind="css:{'preview': isPreview, 'container': containPage}" class="container">

        @await Html.PartialAsync("_TBHeader")

        @*<header class="esh-app-header">
            <div class="container">
                <article class="row">

                    <section class="col-lg-7 col-md-6 col-12">
                        <a class="navbar-brand" routerLink="catalog">
                            <a asp-area="" asp-controller="Catalog" asp-action="Index">
                                <img src="~/images/brand.png" />
                            </a>
                        </a>
                    </section>

                    @await Html.PartialAsync("_LoginPartial")
                </article>
            </div>
        </header>*@

        @RenderBody()


        @*<footer class="esh-app-footer">
            <div class="container">
                <article class="row">

                    <section class="col-sm-6">
                        <img class="esh-app-footer-brand" src="~/images/brand_dark.png" />
                    </section>

                    <section class="col-sm-6">
                        <img class="esh-app-footer-text hidden-xs" src="~/images/main_footer_text.png" width="335" height="26" alt="footer text image" />
                    </section>

                </article>
            </div>
        </footer>*@

        @await Html.PartialAsync("_TBFooter")

    </div>
    <environment names="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)


    @using Microsoft.AspNetCore.Authentication;
    @using Microsoft.Extensions.Options
    @inject IOptions<AppSettings> settings

    <script type="text/javascript">
    if ('@User.Identity.IsAuthenticated' === 'True') {
        var timerId;

        stablishConnection((conn) => registerNotificationHandlers(conn));
    }

    function stablishConnection(cb) {
        let connection = new signalR.HubConnectionBuilder()
            .withUrl('@settings.Value.SignalrHubUrl/hub/notificationhub', {
                transport: signalR.HttpTransportType.LongPolling,
                accessTokenFactory: () => {
                    return "Authorization", getToken();
                }
            })
            .build();

        connection.start().then(function () {
            console.log('User Registered to Signalr Hub');
            cb(connection);
        });
    }

    function registerNotificationHandlers(connection) {
        connection.on("UpdatedOrderState", (message) => {
            toastr.success('Updated to status: ' + message.status, 'Order Id: ' + message.orderId);
            if (window.location.pathname.split("/").pop() === 'Order') {
                refreshOrderList();
            }
        });
    }

    function getToken() {
        return '@Context.GetTokenAsync("access_token").Result';
    }

    function refreshOrderList() {
        clearTimeout(timerId);
        timerId = setTimeout(function () {
            window.location.reload();
        }, 1000);
    }
    </script>

</body>
</html>

src/Web/Websites/ToscaBlu/Views/Shared/_TBFooter.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <div data-bind="template: {name: templateUrl(),templateSrc: templateSrc()}, attr: {id: typeId()+&quot;-&quot;+id()}, visible:($masterViewModel.storeConfiguration.enablePrioritizedLoading) ? (occPrioritizedDisplay ? occPrioritizedDisplay : true):true" id="webContent_v2-wi200066">
        <!-- ko setContextVariable: {name: 'elementConfig', value: {
          "200077": {
            "id": "200077",
            "padding": {
              "paddingBottom": "0",
              "paddingLeft": "0",
              "paddingRight": "0",
              "paddingTop": "0"
            },
            "richText": {
              "content": "<footer class=\"col-xs-12 footer\">\n<div class=\"footer-container\">\n<div class=\"footer-btm\" id=\"newsletter\"><span class=\"title\">ISCRIVITI ALLA NEWSLETTER<\/span> <span class=\"subtitle\">E ricevi news e promozioni<\/span> <input placeholder=\"Inserisci la tua mail\" type=\"text\" \/>\n<p class=\"newsletter-button\"><a data-toggle=\"modal\" href=\"#CC-newsletterModalPanel\" id=\"CC-JoinNewsletter\" style=\"color:#fff!important\">Iscriviti <\/a><\/p>\n<\/div>\n\n<div class=\"footer-btm first\"><span class=\"title\">Servizio clienti<\/span>\n\n<div class=\"footer-links\"><a href=\"\/paymentMethod\">Metodo di pagamento<\/a><a href=\"\/shipping\">Spedizioni<\/a><a href=\"\/returns\">Resi<\/a><a href=\"\/termsAndConditions\">Termini e condizioni<\/a><a href=\"\/contactUs\">Contattaci<\/a><\/div>\n<\/div>\n\n<div class=\"footer-btm\"><span class=\"title\">Corporate<\/span>\n\n<div class=\"footer-links\"><a href=\"\/storelocator\">Store Locator<\/a><\/div>\n\n<div class=\"footer-links\"><a href=\"\/corporate\">Company Profile<\/a><\/div>\n\n<div class=\"footer-links\"><a href=\"\/category\/press\">Press<\/a><\/div>\n\n<div class=\"footer-links\"><a href=\"\/dealers\">Rivenditori e Agenti<\/a><\/div>\n<\/div>\n\n<div class=\"footer-btm\"><span class=\"title\">Privacy<\/span>\n\n<div class=\"footer-links\"><a href=\"\/privacy\">Informativa sulla privacy e cookie policy<\/a><\/div>\n<\/div>\n\n<div class=\"footer-btm last\"><span class=\"title\">SOCIAL<\/span>\n\n<div class=\"footer-links\"><a class=\"instagram-link\" href=\"https:\/\/www.instagram.com\/toscabluofficial\/\" target=\"_blank\">Instagram<\/a><a class=\"facebook-link\" href=\"https:\/\/www.facebook.com\/TOSCABLUOFFICIAL\/\" target=\"_blank\">Facebook<\/a><\/div>\n<\/div>\n<\/div>\n<\/footer>\n",
              "sourceMedia": "m20156"
            }
          },
          "200078": {
            "id": "200078",
            "padding": {
              "paddingBottom": "0",
              "paddingLeft": "0",
              "paddingRight": "0",
              "paddingTop": "0"
            },
            "richText": {
              "content": "<div class=\"footer-info\">\n<p><span>MINORONZONI s.r.l. - Sede amministrativa: <\/span><span>Via E.Fermi - 24036 Ponte S.Pietro (BG) <span class=\"scorr\">-<\/span> <span>Tel. 035.467111 - Fax 035.467142 <\/span><span class=\"scorr\">-<\/span> <span>E-mail: toscablu@minoronzoni.it<\/span><\/span><\/p>\n\n<p><span>Cop. Soc. &euro; 7.000.000,00 - C.C.I.A.A. Bergamo n.225081<\/span> <span class=\"scorr\">-<\/span> <span>Tribunale di Bergamo Rag. Soc. 28080<\/span> <span class=\"scorr\">-<\/span> C.F. e P.IVA 01638680163<\/p>\n\n<p class=\"info-brand\">powered by IBOX SA<\/p>\n<\/div>\n",
              "sourceMedia": "m20158"
            }
          }
        }} -->
        <!-- /ko -->
        <!-- oc layout: panels -->
        <div class="row">

            <div class="oc-panel col-md-12" data-oc-id="panel-0-0">

                <!-- oc section: rich-text -->
                <span data-bind="element: 'rich-text',id: '200077'" id="wi200066-rich-text-200077">
                    <!-- ko with: $elementInstance -->
                    <!-- ko if: ($data.hasOwnProperty('config') && $data.id !== 'id') -->
                    <div class="cc-rich-text" data-bind="style: {paddingTop: config.padding.paddingTop + 'px', paddingBottom: config.padding.paddingBottom + 'px', paddingLeft: config.padding.paddingLeft + 'px', paddingRight: config.padding.paddingRight + 'px'}, html: config.richText.content" style="padding: 0px;">
                        <footer class="col-xs-12 footer">
                            <div class="footer-container">
                                <div class="footer-btm" id="newsletter">
                                    <span class="title">ISCRIVITI ALLA NEWSLETTER</span> <span class="subtitle">E ricevi news e promozioni</span> <input placeholder="Inserisci la tua mail" type="text">
                                    <p class="newsletter-button"><a data-toggle="modal" href="#CC-newsletterModalPanel" id="CC-JoinNewsletter" style="color:#fff!important">Iscriviti </a></p>
                                </div>

                                <div class="footer-btm first">
                                    <span class="title">Servizio clienti</span>

                                    <div class="footer-links"><a href="https://www.toscablu.com/it-IT/paymentMethod">Metodo di pagamento</a><a href="https://www.toscablu.com/it-IT/shipping">Spedizioni</a><a href="https://www.toscablu.com/it-IT/returns">Resi</a><a href="https://www.toscablu.com/it-IT/termsAndConditions">Termini e condizioni</a><a href="https://www.toscablu.com/it-IT/contactUs">Contattaci</a></div>
                                </div>

                                <div class="footer-btm">
                                    <span class="title">Corporate</span>

                                    <div class="footer-links"><a href="https://www.toscablu.com/it-IT/storelocator">Store Locator</a></div>

                                    <div class="footer-links"><a href="https://www.toscablu.com/it-IT/corporate">Company Profile</a></div>

                                    <div class="footer-links"><a href="https://www.toscablu.com/it-IT/category/press">Press</a></div>

                                    <div class="footer-links"><a href="https://www.toscablu.com/it-IT/dealers">Rivenditori e Agenti</a></div>
                                </div>

                                <div class="footer-btm">
                                    <span class="title">Privacy</span>

                                    <div class="footer-links"><a href="https://www.toscablu.com/it-IT/privacy">Informativa sulla privacy e cookie policy</a></div>
                                </div>

                                <div class="footer-btm last">
                                    <span class="title">SOCIAL</span>

                                    <div class="footer-links"><a class="instagram-link" href="https://www.instagram.com/toscabluofficial/" target="_blank">Instagram</a><a class="facebook-link" href="https://www.facebook.com/TOSCABLUOFFICIAL/" target="_blank">Facebook</a></div>
                                </div>
                            </div>
                        </footer>
                    </div>
                    <!-- /ko -->
                    <!-- /ko -->

                </span>

                <!-- /oc -->
                <!-- oc section: rich-text -->
                <span data-bind="element: 'rich-text',id: '200078'" id="wi200066-rich-text-200078">
                    <!-- ko with: $elementInstance -->
                    <!-- ko if: ($data.hasOwnProperty('config') && $data.id !== 'id') -->
                    <div class="cc-rich-text" data-bind="style: {paddingTop: config.padding.paddingTop + 'px', paddingBottom: config.padding.paddingBottom + 'px', paddingLeft: config.padding.paddingLeft + 'px', paddingRight: config.padding.paddingRight + 'px'}, html: config.richText.content" style="padding: 0px;">
                        <div class="footer-info">
                            <p><span>MINORONZONI s.r.l. - Sede amministrativa: </span><span>Via E.Fermi - 24036 Ponte S.Pietro (BG) <span class="scorr">-</span> <span>Tel. 035.467111 - Fax 035.467142 </span><span class="scorr">-</span> <span>E-mail: toscablu@minoronzoni.it</span></span></p>

                            <p><span>Cop. Soc. € 7.000.000,00 - C.C.I.A.A. Bergamo n.225081</span> <span class="scorr">-</span> <span>Tribunale di Bergamo Rag. Soc. 28080</span> <span class="scorr">-</span> C.F. e P.IVA 01638680163</p>

                            <p class="info-brand">powered by IBOX SA</p>
                        </div>
                    </div>
                    <!-- /ko -->
                    <!-- /ko -->

                </span>
                <!-- /oc -->

            </div>


        </div>
        <!-- /oc -->
    </div>
}

src/Web/Websites/ToscaBlu/Views/Shared/_TBLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.eShopOnContainers.WebMVC.ViewModels
@using Microsoft.eShopOnContainers.WebMVC.Services

@inject IIdentityParser<ApplicationUser> UserManager
@*@if (Context.User.Identity.IsAuthenticated)*@







<div id="userIcon">
    <!-- ko with: user -->
    <!-- ko if: readyToDisplay -->
    <div class="text-right cc-welcome">

        @if (User.FindFirst(x => x.Type == "preferred_username") != null)
        {
            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                <ul class="nav navbar-nav navbar-right" style="display:none;">
                    <li>
                        <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage"></a>
                    </li>
                    <li>
                        <button type="submit" class="btn btn-link navbar-btn navbar-link">Log off</button>
                    </li>
                </ul>
            </form>

            <div data-bind="visible: loggedInUserName() &amp;&amp; (loggedIn() || isUserSessionExpired()) ">
                <div id="oldLoggedIn" style="display: none">
                    <strong><span data-bind="widgetLocaleText : {value:'welcome', attr:'innerText', params: {userName: loggedInUserName()}}" class="cc-header-firstName">Benvenuto/a Samuele</span></strong>
                    <span>
                        <a id="CC-loginHeader-myAccount" data-original-title="myAccount" data-bind="widgetLocaleText: {attr: 'innerText', value: 'myAccount'}, click: validatePrivilagePageRequest, ccNavigation: 'prevent', ccLink: 'profile'" href="/it-IT/profile">Account personale</a>
                    </span>|
                    <span>
                        <a id="CC-loginHeader-logout" data-original-title="logout" data-bind="widgetLocaleText: {attr: 'innerText', value: 'logoutLinkText'}, click: $parent['elements']['login-registration-v2'].handleLogout.bind($parent)" href="#">Esci</a>
                    </span>
                </div>
                <a href="/Account/SignOut"><img class="headerIcon" src="~/images/tb/user2_loggedIn.png"></a>
            </div>





        }
        else
        {
            <div data-bind="visible: !(loggedInUserName() &amp;&amp; (loggedIn() || isUserSessionExpired()))">
                <a asp-area="" asp-controller="Account" asp-action="SignIn" class="esh-identity-name esh-identity-name--upper">
                    <!--<img class="header-icon" src="/file/general/user.svg" />-->
                    <img class="headerIcon" src="~/images/tb/user2.png">
                </a>
            </div>


        }
    </div>
    <!-- /ko -->
    <!-- /ko -->
</div>
@if (User.FindFirst(x => x.Type == "preferred_username") != null)
{
    @await Component.InvokeAsync("Cart", new { user = UserManager.Parse(User) })
}
else
{

    <div class="row" id="minicartRow">
        <h2 class="label-hidden" data-bind="widgetLocaleText : 'shoppingCartHeader'">Riepilogo carrello</h2>
        <div class="col-xs-12 hidden-xs" id="dropdowncart">
            <div class="pull-right">
                <h3 class="label-hidden" data-bind="widgetLocaleText : 'cartOperationsText'">Operazioni carrello</h3>
                <div class="minicart-heading">
                    <!--<span class="glyphicon glyphicon-shopping-cart"></span>-->
                    <a data-bind="with: cart, click: toggleDropDownCart, widgetLocaleText: {attr: 'aria-label', value: 'miniShoppingCartTitle'}, event: {keydown: $data.keypressHandler}" href="#" id="CC-header-cart-total" data-original-title="Shopping Cart" class="cc-cartlink-anchor" aria-label="Mini carrello">
                        <!--<span data-bind="text: cartLinkText"></span>-->


                        <img class="headerIcon" id="basketIcon" src="~/images/tb/basket2.png">
                        <p class="minicartItemsNumber" data-bind="text: numberOfItems">0</p>


                    </a>
                </div>

            </div>

        </div>
    </div>
}